### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by PeterVila** [PeterVila/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create index.html and link stylesheets(s)
- [x] Add an icon to the page
- [x] Set a background-color for the whole page
- [x] Set the given car image on the page.
