### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by PeterVila** [PeterVila/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Link script file in html
- [x] Create your data model for identifying which way the car is facing
- [x] Add event listeners for keydowns (left, right etc...)
- [x] Push the direction into data model.
- [x] Add a new class which allows rotating the car 90 degrees depend on what is clicked
- [x] Add a condition so car doesn't turn 270degrees to get to left and right.
