### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by PeterVila** [PeterVila/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Create an event listener for keydowns 
- [x] If the keydown is 'space' set up a new css property to move position.
- [x] Every space should turn the data object property to true or false.
- [x] Based on the current value of the property in data object, use position to move the car that direction.
- [x] Create an interval on the car to move every 16 ms
