### ISSUE TITLE
User can stop their car

### ISSUE THREAD

**Issue by PeterVila** [PeterVila/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [ ] Within space keydown event, look at the value of the property if car is starting to move
- [ ] If that value is true, another click would set it to false
- [ ] If false, stop the car.
